### PR TITLE
second commit refactored total fun

### PR DESCRIPTION
**Pull request by bevennyamande**
refactored the total function and updated the readme file for the total method

### CODE REVIEW

**Review by bevennyamande — COMMENTED** [review]
review the changes I made

**Comment by bevennyamande** [comment]
Still fixing and refactoring

**Review by bevennyamande — COMMENTED** [review]
Still fixing and refactoring

**Comment by iammerus** [comment]
Hi @bevennyamande.  I do not see any changes that this PR is bringing to the SDK. If you could please add a bit more information about what you did

**Review by iammerus — COMMENTED** [review]
Hi @bevennyamande.  I do not see any changes that this PR is bringing to the SDK. If you could please add a bit more information about what you did

**Comment by bevennyamande** [comment]
Your total function, did you note issues with decimals ie rounding up/down?

**Comment by iammerus** [comment]
Mmm, not in the rests I'd run. Did you run into any issues with the total function? Can you please post the code I can use to reproduce the issue you can into?

**Pull request closed without merging**
