### PR TITLE
Paynow-Python SDK python 3 to 2 migration

### PR DESCRIPTION
**Pull request by ignertic**

### CODE REVIEW

**Comment by iammerus** [comment]
Hi @ignertic. Can you please briefly outline what you did? **Python 2 Support** is a bit too obscure a commit message.  What changes did you make that led to the support of Python 2?

**Review by ignertic — COMMENTED** [review]
Removed explicit type declarations and refactored imports, "parse_qs" & "quote_plus" are now imported from the six library

**Review by iammerus — CHANGES_REQUESTED** [review]
Okay awesome! Nice catch on the **urllib.parse** import and the type annotations. However, can you please add a commit that adds type annotations for function by using comments?

We use a documentation generator that makes use of type annotations to generate source docs.

**Review by ignertic — COMMENTED** [review]
Removed explicit type declarations. 
Refactored "quote_plus" and "parse_qs" imports

**Review by iammerus — APPROVED** [review]

**Pull request merged**
